config/routes.rb
MleApp::Application.routes.draw do

  get "dashboard/new"
  get "sessions/new"

  get "pages/home"
  resources :indicators
  root :to => 'pages#home'
  
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'nigeria', to: "pages#nigeria_profile"
  get 'reports', to: "pages#reports"
  
  get 'baseline_survey', to: "pages#baseline_survey"

  # Dashboard stuff
  get 'behavior', to: "pages#behavior"
  get 'community', to: "pages#community"
  get 'nigeria/dashboard', to: "dashboard#main"
  get 'nigeria/care_seeking', to: "pages#care_seeking"
  get 'nigeria/behavior', to: "pages#behavior"
  get 'nigeria/community', to: "pages#community"
  get 'nigeria/treatment_coverage', to: "pages#treatment_coverage"
  
  get 'dashboard', to: "dashboard#main"

  resources :sessions

end

app/models/condition.rb
class Condition < ActiveRecord::Base
  #attr_accessible :description, :name
end

app/models/indicator.rb
class Indicator < ActiveRecord::Base
  #attr_accessible :name, :definition, :metric, :condition, :survey_method

  belongs_to :survey_method
  belongs_to :condition
end

app/models/survey_method.rb
class SurveyMethod < ActiveRecord::Base
  #attr_accessible :description, :name
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :encrypt_password

  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "authenticated"

  def new
  end

  def main

  end



end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @indicators }
    end
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
    @indicator = Indicator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @indicator }
    end
  end

  # GET /indicators/new
  # GET /indicators/new.json
  def new
    @indicator = Indicator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @indicator }
    end
  end

  # GET /indicators/1/edit
  def edit
    @indicator = Indicator.find(params[:id])
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(params[:indicator])

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render json: @indicator, status: :created, location: @indicator }
      else
        format.html { render action: "new" }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /indicators/1
  # PUT /indicators/1.json
  def update
    @indicator = Indicator.find(params[:id])

    respond_to do |format|
      if @indicator.update_attributes(params[:indicator])
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator = Indicator.find(params[:id])
    @indicator.destroy

    respond_to do |format|
      format.html { redirect_to indicators_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "authenticated"

  def home
  end

  def nigeria_profile

  	

  end

  def india_profile
  end

  def reports
  end

  # drill downs
  def behavior
  	
  end

  def community
  	
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      #render js: %(window.location.href='#{root_url}')
      render text: "OK"
    else
      head :unauthorized
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(app_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

private
  def app_params
    params.require(:user).permit(:password, :email, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/indicators_helper.rb
module IndicatorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/main.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a> / </li>
   <li><a href="/nigeria">Nigeria</a> / </li>
  <li class="active"> Dashboard </li>
</ol>

<div class="row show-grid">
  <div class="span5">
    <h1>Nigeria</h1>
  </div>
</div>

<ul class="nav nav-tabs nav-justified">
  <li><a href="/nigeria">Country Profile</a></li>
  <li class="active"><a href="/nigeria/dashboard">Dashboard</a></li>
</ul>


<h3 style="margin-bottom: 40px">Treatment of the sick child theory of change</h3>

<div id="mainPanel">

<div class="vertical" >
    <%= image_tag("market.png")%> 
</div>

<div class="verticleColumn" id="activities">
     <div class="window activities" id="chartWindow1">
     	<h4>
     		<span style="text-align: center">Activities</span>
     	</h4>
     </div>
     <div class="window bmgf_activities" id="chartWindow2" title="BMGF Funded">
      Behavior change /care seeking messaging

      <div class="dashboard_notes">
        <p>3 radio programs aired, 300 times, over 2 years</p>
        <p>200 CBO leaders trained</p>
      </div>
     </div>

     <div class="window activities" id="chartWindow3">
        Strengthen policy
     </div>
     <div class="window activities" id="chartWindow4">
      Training providers: private and public
    </div>
     <div class="window no_activities" id="chartWindow5">
      New tools and systems for providers
     </div>
     <div class="window activities" id="chartWindow6">
      Improve supply of commodities 
     </div>
     <div class="window no_activities" id="chartWindow7">
      Improve presentation of treatments
     </div>
  </div> 

  <div class="verticleColumn" id="functions">
     <div class="window functions" id="chartWindow10"><h4>Health system functions</h4></div>
     <div class="window functions" id="chartWindow11">
      Community empowered

            <table class="small_table" style="margin-top: 10px">
               <tr>
                  <th>Indicator</th>
                  <th>2014</th>
                  <th>2016</th>
               </tr>
               <tr>
                  <th>Knowledge of symptoms D&P</th>
                  <td>40%</td>
                  <td>80%</td>
               </tr>
               <tr>
                  <th>Indicator X</th>
                  <td>12.2</td>
                  <td>15</td>
               </tr>
              <tr>
                  <th>Indicator Y</th>
                  <td>12.2</td>
                  <td>15</td>
              </tr>
              <tr>
                  <th>Indicator Z</th>
                  <td>393</td>
                  <td>455</td>
              </tr>
             </table>


      </div>
     <div class="window functions" id="chartWindow12">
      Financing
    </div>
     <div class="window functions" id="chartWindow13">
      Governance and leadership
    </div>
     <div class="window functions" id="chartWindow14">
      Health information
      </div>
     <div class="window functions" id="chartWindow15">
      Human resources - PUBLIC
    </div>
     <div class="window functions" id="chartWindow16">
      Human resources - PRIVATE
     </div>
     <div class="window functions" id="chartWindow17">
      Medicines equipment and commodities
    </div>
  </div>    

  <div class="verticleColumn" id="outputs">
     <div class="window outputs" id="chartWindow18">
        <h4>Outputs</h4>
      </div>
     <div class="window outputs" id="chartWindow19" >
        Care seeking

              <table class="small_table" style="margin-top: 10px">
               <tr>
                  <th>Indicator</th>
                  <th>2014</th>
                  <th>2016</th>
               </tr>
               <tr>
                  <td>Care seeking for D/P</td>
                  <td>30%</td>
                  <td>45%</td>
               </tr> 
             </table>


      </div>
     <div class="window outputs" id="chartWindow20" style="margin-top: 50px">
        Availability of quality care and treatment
    </div>  
  </div>  

  <div class="verticleColumn" id="outcome">
  	<div class="window outcomes" id="chartWindow21"><h4>Outcome</h4></div>
  	<div class="window outcomes" id="chartWindow22">
      Quality treatment coverage
	</div>
  </div>

  <div class="verticleColumn" id="goals">
  	<div class="window goals" id="chartWindow23"><h4>Goal</h4></div>
  	<div class="window goals" id="chartWindow24">
        Improved Child Survival

      <div class="dashboard_notes">
        <p>Number lives saved: 1,213</p>
        <p>Cost per life saved: $23</p>
      </div>

	</div>
  </div>
</div>

<div id="spacer" style="height: 50px; clear: both">
  </div>
 
<div id="horizontal">
  	<div>
  		<h5>Context</h5>Ratio of private to public use of services; service utilization rates; transportation; maternal education and woman empowerment;  activities of other partners working in this space; etc
  	</div>
</div>

<div id="spacer" style="height: 50px; clear: both">
  </div>
  

app/views/dashboard/new.html.erb
<h1>Dashboard#new</h1>
<p>Find me in app/views/dashboard/new.html.erb</p>

app/views/indicators/_form.html.erb
<%= form_for @indicator, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>

    <%= f.label :definition, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :definition, :class => 'text_area' %>
    </div>

    <%= f.label :metric, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :metric, :class => 'text_area' %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                indicators_path, :class => 'btn' %>
  </div>
<% end %>

app/views/indicators/edit.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/indicators/index.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a> / </li>
  <li class="active"> Indicators </li>
</ol>


<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Condition</th>
      <th>Survey Method</th>
    </tr>
  </thead>
  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td width="30%"><%= link_to indicator.name, indicator_path(indicator) %></td>
        <td><%= indicator.condition.name %></td>
        <td><%= indicator.survey_method.name %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_indicator_path,
            :class => 'btn btn-primary' %>

app/views/indicators/new.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/indicators/show.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @indicator.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:definition) %>:</strong></dt>
  <dd><%= @indicator.definition %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:metric) %>:</strong></dt>
  <dd><%= @indicator.metric %></dd>
</dl>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              indicators_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_indicator_path(@indicator), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              indicator_path(@indicator),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project MLE Sick Child Initiative</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
   <%= stylesheet_link_tag  params[:controller], :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>


<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Project Sick Child Initiative</a>
        
        <div class="nav-collapse">

          <ul class="nav">
            <li><%= link_to "Browse Indicators", indicators_path %></li>
            <li><%= link_to "Nigeria", nigeria_url %></li>
          </ul>

          <ul class="nav pull-right">
            <% if current_user %>
              <li style="padding: 10px 15px"> 
                Logged in as <%= current_user.email %> <%= link_to "Log out", log_out_path, {:style=>'display:inline;'} %>
              </li>
            <% else %>
              <li>
                <a data-toggle="modal" href="#login-modal" >Login</a>
              </li>
            <% end %>
          </ul>
        </div>
       
      </div>
    </div>
  </div>
	
<div class="container">

  <!-- Modal -->
  <div class="modal hide fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Login</h4>
        </div>
        <div class="modal-body">

          <div id="login-message" class="alert alert-danger hide"></div>
             
          <%= form_tag sessions_path  do %>
            <p>
              <%= label_tag :email %><br />
              <%= text_field_tag :email, params[:email] %>
            </p>
            <p>
              <%= label_tag :password %><br />
              <%= password_field_tag :password %>
            </p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button id="login-button" type="button" class="btn btn-primary ">Login</button>
        </div>
      </div>
    </div>
  </div>


	<div class="row">
		<div class="span9"><%= yield %></div>
		<div class="span3">
			<h2>About this Project</h2>
			At the end of 2012, the Bill & Melinda Gates Foundation leadership approved a cross-cutting strategy for the integrated treatment of childhood illnesses. The initiative is managed by the Integrated Delivery team and works across the Enteric and Diarrheal Diseases, Pneumonia, Malaria and Family Health Program Strategy Teams. The team works to improve access to effective treatment for sick children with a particular focus on three geographical areas: Burkina Faso, Nigeria and northern India. The cross-cutting approach of the initiative offers the opportunity to consider and implement solutions which contribute to the goals of several disease-specific strategy teams at once. 
		</div>
	</div>

</div>


</body>
</html>

app/views/layouts/authenticated.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project MLE Sick Child Initiative</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<div id="wrap">

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Project MLE Sick Child Initiative</a>
        
        <div class="nav-collapse">

          <ul class="nav">
            <li><%= link_to "Browse Indicators", indicators_path %></li>
            <li><%= link_to "Nigeria", nigeria_url %></li>
          </ul>

          <ul class="nav pull-right">
            <% if current_user %>
              <li style="padding: 10px 15px"> 
                Logged in as <%= current_user.email %> <%= link_to "Log out", log_out_path, {:style=>'display:inline;'} %>
              </li>
            <% else %>
              <li>
                <a data-toggle="modal" href="#login-modal" >Login</a>
              </li>
            <% end %>
          </ul>
        </div>
       
      </div>
    </div>
  </div>
  
<div class="container">

  <!-- Modal -->
  <div class="modal hide fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Login</h4>
        </div>
        <div class="modal-body">

          <div id="login-message" class="alert alert-danger hide"></div>
             
          <%= form_tag sessions_path  do %>
            <p>
              <%= label_tag :email %><br />
              <%= text_field_tag :email, params[:email] %>
            </p>
            <p>
              <%= label_tag :password %><br />
              <%= password_field_tag :password %>
            </p>
          <% end %>
        </div>
        <div class="modal-footer">
          <button id="login-button" type="button" class="btn btn-primary ">Login</button>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
      <div class="span12"><%= yield %></div>
    </div>
  </div>

</div>


<div id="footer">
  <div class="container">
    <p class="text-muted">
      Gates Foundation
    </p>
  </div>
</div>


</body>
</html>

app/views/pages/baseline_survey.erb
<h2>Baseline Survey</h2>

app/views/pages/behavior.html.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a> / </li>
  <li><a href="/nigeria">Nigeria</a> / </li>
  <li><a href="/nigeria/dashboard">Dashboard</a> / </li>
  <li class="active">Behavior change/care seeking messaging</li>
</ol>

<div class="page-header">
  <h2>Behavior change care seeking messaging<small> Mass media, ICT, CBOs, women’s groups
</small></h2>
</div>


  

<div class="row show-grid">
	<div class="span6">
		
		<table class="table">
			   <tr>
			   		<th>Grant</th>
			   		<th>Key Indicators</th>
			   </tr>
			   <tr>
			   		<td rowspan="3">
			   				<div>BBC MA</div>
							<div>2013-2016</div>
							<div>Demand: Support communications campaign promoting appropriate treatment of childhood illness in Nigeria</div>
			   		</td>
			   		<td>Indicator 1</td>
			   </tr>
			   <tr>
			   	<td>Indicator 2</td>
			   </tr>
			   <tr>
			   	<td>Indicator 3</td>
			   </tr>
			 </table>


	</div>
</div>

app/views/pages/community.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a> / </li>
  <li><a href="/nigeria">Nigeria</a> / </li>
  <li><a href="/nigeria/dashboard">Dashboard</a> / </li>
  <li class="active">Community Empowered</li>
</ol>

<div class="page-header">
  <h2>Community Empowered <small> preferences and empowerment</small></h2>
</div>


<div class="row show-grid">
  <div class="span6">
    
    <table class="table">

         <tr>
            <th>Indicator</th>
            <th>2014</th>
            <th>2016</th>
         </tr>
         <tr>
            <th>Knowledge of symptoms D&P</th>
            <td>40%</td>
            <td>80%</td>
         </tr>
         <tr>
            <th>Indicator X</th>
            <td>12.2</td>
            <td>15</td>
         </tr>
        <tr>
            <th>Indicator Y</th>
            <td>12.2</td>
            <td>15</td>
        </tr>
        <tr>
            <th>Indicator Z</th>
            <td>393</td>
            <td>455</td>
        </tr>
       </table>


  </div>
</div>

app/views/pages/dashboard.erb
<select>
	<option name="nigeria">Nigeria</option>
	<option name="india">India</option>
</select>


<h1>Treatment of the sick child delivery sub-program theory</h1>

<div id="mainPanel">

<div class="vertical" >
	<div class="rotate">
    Market Research
  </div>
</div>

<div class="verticleColumn" id="activities">
     <div class="window activities" id="chartWindow1">
     	<h4>
     		<span style="text-align: center">BMGF-funded Activities</span>
     	</h4>
     </div>
     <div class="window activities" id="chartWindow2">

      Behavior change /care seeking messaging in:
      <ul>
      <li>Mass media</li>
      <li>ICT</li>
      <li>CBOs, women’s groups</li>
      </ul>
     </div>

     <div class="window activities" id="chartWindow3">
        Coordination/collaboration with government entities for enabling policy , implementation, dissemination
     </div>
     <div class="window activities" id="chartWindow4">
      Training, detailing, networking health providers (public, private)
    </div>
     <div class="window activities" id="chartWindow5">
      New tools and systems  to improve providers’ care (public, private)
     </div>
     <div class="window activities" id="chartWindow6">
      Increasing supply of  existing  1st line treatment (ORS, zn, amox) supply to  community facilities (by type)
     </div>
     <div class="window activities" id="chartWindow7">
      Improved treatment presentations  delivered (ORS, zn, amox) 
     </div>
  </div> 

  <div class="verticleColumn" id="functions">
     <div class="window functions" id="chartWindow10"><h4>Health system functions</h4></div>
     <div class="window functions" id="chartWindow11">
      Community knowledge, preferences and empowerment
      </div>
     <div class="window functions" id="chartWindow12">
      Financing (program funding, fees for services, fees for drugs)
    </div>
     <div class="window functions" id="chartWindow13">
      Governance and leadership
    </div>
     <div class="window functions" id="chartWindow14">
      Health information (on commodities, treatments, disease, resources, etc)
      </div>
     <div class="window functions" id="chartWindow15">
      Human resources (#, knowledge, skills) - PUBLIC
    </div>
     <div class="window functions" id="chartWindow16">
      Human resources (#, knowledge, skills) - PRIVATE
     </div>
     <div class="window functions" id="chartWindow17">
      Medicines equipment and commodities
    </div>
  </div>    

  <div class="verticleColumn" id="outputs">
     <div class="window outputs" id="chartWindow18">
        <h4>Outputs</h4>
      </div>
     <div class="window outputs" id="chartWindow19">
        <span style="font-weight:bold;">Prompt care seeking</span> (Demand)
      </div>
     <div class="window outputs" id="chartWindow20">
      <span style="font-weight:bold;">Availability of quality care and treatment</span>  (Supply)
        <ul>
          <li>Stability in available stock</li>
          <li>Provider behaviors (diagnosis, treatment, attitude)</li>
          <li>Access to providers</li>
        </ul>
      </div>  
  </div>  

  <div class="verticleColumn" id="outcome">
  	<div class="window outcomes" id="chartWindow21"><h4>Outcome</h4></div>
  	<div class="window outcomes" id="chartWindow22">
      <span style="font-weight:bold;">Quality treatment coverage</span>
      Increase in percent of children receiving timely and appropriate care for pneumonia, diarrhea and malaria
	</div>
  </div>

  <div class="verticleColumn" id="goals">
  	<div class="window goals" id="chartWindow23"><h4>Goal</h4></div>
  	<div class="window goals" id="chartWindow24">
        <span style="font-weight:bold;">Improved Child Survival</span>
	       <ul>
          <li>Cost per DALY averted</li>
	        <li>Cost per life saved</li>
	         <li>(Equity, Scale)</li>
	</div>
  </div>


</div>
 
<div id="horizontal">
  	<div>
  		<h5>Context</h5>Ratio of private to public use of services; service utilization rates; transportation; maternal education and woman empowerment;  activities of other partners working in this space; etc
  	</div>
</div>

app/views/pages/india_profile.erb
<h2>India </h2>
<h4>Country Profile</h4>

app/views/pages/reports.erb
<h2>Reports</h2>

app/views/pages/treatment_coverage.erb
<ol class="breadcrumb">
  <li><a href="/">Home</a> / </li>
  <li><a href="/nigeria">Nigeria</a> / </li>
  <li><a href="/nigeria/dashboard">Dashboard</a> / </li>
  <li class="active">Quality Treatment Coverage</li>
</ol>

<div class="page-header">
  <h2>Quality Treatment Coverage <small> Increase in percent of children receiving timely and appropriate care</small></h2>
</div>


<div class="row show-grid">
  <div class="span6">
    
    <table class="table">

         <tr>
            <th>Indicator</th>
            <th>2014</th>
            <th>2016</th>
         </tr>
         <tr>
            <td>Treatment coverage diarrhea</td>
            <td>20%</td>
            <td>30%</td>
         </tr>

       </table>


  </div>
</div>